# Site settings
title: Jordan Wu Blog Site
email: jordan.spencer.wu@gmail.com
description: Jordan Wu personal blog
url: "http://JordanSpencerWu.github.io" # the base hostname & protocol for your site

# Pagination
permalink: /:year/:month/:day/:title/
paginate: 5

# Gems
gems: ['jekyll-paginate']

# Disqus comments configuration
disqus_shortname: jordanwu

# Build settings
markdown: kramdown
