# Site settings
title: Jordan Wu Blog Site
email: jordan.spencer.wu@gmail.com
description: JordanSpencerWu Personal Blog
url: "https://JordanSpencerWu.github.io" # the base hostname & protocol for your site
author: Jordan Wu

# Pagination
permalink: /:year/:month/:day/:title/
paginate_path: "page:num"
paginate: 5

# Gems
gems: [jekyll-paginate, jekyll-sitemap]

# Disqus comments configuration
disqus_shortname: jordanwu

# Build settings
markdown: kramdown

# Site map
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"