# Site settings
title: Jordan Wu Blog Site
email: jordan.spencer.wu@gmail.com
description: Jordan Wu personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JordanSpencerWu.github.io" # the base hostname & protocol for your site

# Pagination
paginate: 5

# Gems
gems: ['jekyll-paginate']

# Build settings
markdown: kramdown
